//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SecureDBEntities : DbContext
    {
        public SecureDBEntities()
            : base("name=SecureDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwAIImmediatelyCheck> vwAIImmediatelyCheck { get; set; }
        public DbSet<vwAlarmLog> vwAlarmLog { get; set; }
        public DbSet<vwAllAlarmLog> vwAllAlarmLog { get; set; }
        public DbSet<vwCardCommandLog> vwCardCommandLog { get; set; }
        public DbSet<vwControllerConfig> vwControllerConfig { get; set; }
        public DbSet<vwDeviceStateLog> vwDeviceStateLog { get; set; }
        public DbSet<vwEngineRoomLog> vwEngineRoomLog { get; set; }
        public DbSet<vwEntranceGuardDetail> vwEntranceGuardDetail { get; set; }
        public DbSet<vwERNamePlaneList> vwERNamePlaneList { get; set; }
        public DbSet<vwERNameRTUList> vwERNameRTUList { get; set; }
        public DbSet<vwItemConfig> vwItemConfig { get; set; }
        public DbSet<vwItemGroup> vwItemGroup { get; set; }
        public DbSet<vwMagneticCard> vwMagneticCard { get; set; }
        public DbSet<vwMagneticCardAllowController> vwMagneticCardAllowController { get; set; }
        public DbSet<vwMagneticCardDetail> vwMagneticCardDetail { get; set; }
        public DbSet<vwNVRConfig> vwNVRConfig { get; set; }
        public DbSet<vwPasswordEveryDayDifference> vwPasswordEveryDayDifference { get; set; }
        public DbSet<vwPDAlarmLog> vwPDAlarmLog { get; set; }
        public DbSet<vwPDAlarmLoopDeviceLog> vwPDAlarmLoopDeviceLog { get; set; }
        public DbSet<vwPDConfig> vwPDConfig { get; set; }
        public DbSet<vwPDLoopDeviceConfig> vwPDLoopDeviceConfig { get; set; }
        public DbSet<vwR23DeviceStateLog> vwR23DeviceStateLog { get; set; }
        public DbSet<vwR23EngineRoomLog> vwR23EngineRoomLog { get; set; }
        public DbSet<vwR23HardwareState> vwR23HardwareState { get; set; }
        public DbSet<vwR23ReaderLog> vwR23ReaderLog { get; set; }
        public DbSet<vwReaderAbnormalPassLog> vwReaderAbnormalPassLog { get; set; }
        public DbSet<vwReaderPassList> vwReaderPassList { get; set; }
        public DbSet<vwReaderPassLog> vwReaderPassLog { get; set; }
        public DbSet<vwUserGroupMenuAllow> vwUserGroupMenuAllow { get; set; }
        public DbSet<vwUserMenuAllow> vwUserMenuAllow { get; set; }
    }
}
