//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemGroup
    {
        public tblItemGroup()
        {
            this.tblItemConfig = new HashSet<tblItemConfig>();
        }
    
        public int GroupID { get; set; }
        public Nullable<short> GroupType { get; set; }
        public string GroupName { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
        public double Rotation { get; set; }
        public double ScaleX { get; set; }
        public double ScaleY { get; set; }
        public Nullable<int> PlaneID { get; set; }
        public bool IsShow { get; set; }
    
        public virtual ICollection<tblItemConfig> tblItemConfig { get; set; }
    }
}
