//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSingalIO
    {
        public tblSingalIO()
        {
            this.tblSingalIOLog = new HashSet<tblSingalIOLog>();
        }
    
        public string ControlID { get; set; }
        public string SingalName { get; set; }
        public string SingalType { get; set; }
        public Nullable<short> Place { get; set; }
        public string Memo { get; set; }
    
        public virtual tblControllerConfig tblControllerConfig { get; set; }
        public virtual ICollection<tblSingalIOLog> tblSingalIOLog { get; set; }
    }
}
