//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPDLoopDeviceConfig
    {
        public string PDName { get; set; }
        public short PD_LoopNO { get; set; }
        public string DeviceName { get; set; }
        public string Mapping_DeviceName { get; set; }
        public string Location { get; set; }
        public string LineID { get; set; }
        public string Direction { get; set; }
        public Nullable<int> mile_m { get; set; }
        public string IP { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<double> GPSX { get; set; }
        public Nullable<double> GPSY { get; set; }
        public string device_type { get; set; }
        public string ISBREAKDOWN { get; set; }
        public string Enable { get; set; }
        public string Memo { get; set; }
        public string LineName { get; set; }
        public string DirectionName { get; set; }
        public Nullable<int> Diameter { get; set; }
    }
}
