//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SecureDBEntities1 : DbContext
    {
        public SecureDBEntities1()
            : base("name=SecureDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblERDoorPassword> tblERDoorPassword { get; set; }
        public DbSet<tblEngineRoomLog> tblEngineRoomLog { get; set; }
        public DbSet<tblCardCommandLog> tblCardCommandLog { get; set; }
        public DbSet<tblERPlane> tblERPlane { get; set; }
        public DbSet<tblMagneticCard> tblMagneticCard { get; set; }
        public DbSet<vwMagneticCardAllowController> vwMagneticCardAllowController { get; set; }
        public DbSet<tblCCTVConfig> tblCCTVConfig { get; set; }
        public DbSet<tblNVRConfig> tblNVRConfig { get; set; }
        public DbSet<tblSysParameter> tblSysParameter { get; set; }
        public DbSet<vwMagneticCardDetail> vwMagneticCardDetail { get; set; }
        public DbSet<tblControllerConfig> tblControllerConfig { get; set; }
        public DbSet<tblItemConfig> tblItemConfig { get; set; }
        public DbSet<tblItemGroup> tblItemGroup { get; set; }
        public DbSet<tblAIItem1HourLog> tblAIItem1HourLog { get; set; }
        public DbSet<tblPDConfig> tblPDConfig { get; set; }
        public DbSet<tblPDAlarmLog> tblPDAlarmLog { get; set; }
        public DbSet<tblAlarmLog> tblAlarmLog { get; set; }
        public DbSet<vwMagneticCard> vwMagneticCard { get; set; }
        public DbSet<vwCardCommandLog> vwCardCommandLog { get; set; }
        public DbSet<vwEngineRoomLog> vwEngineRoomLog { get; set; }
        public DbSet<vwEntranceGuardDetail> vwEntranceGuardDetail { get; set; }
        public DbSet<vwUserGroupMenuAllow> vwUserGroupMenuAllow { get; set; }
        public DbSet<vwUserMenuAllow> vwUserMenuAllow { get; set; }
        public DbSet<tblDeviceStateLog> tblDeviceStateLog { get; set; }
    }
}
