//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCardReaderConfig
    {
        public int ReaderID { get; set; }
        public string EntranceCode { get; set; }
        public string ControlID { get; set; }
        public Nullable<short> ReaderType { get; set; }
        public Nullable<short> ReaderNO { get; set; }
        public string RoomIO { get; set; }
    
        public virtual tblControllerConfig tblControllerConfig { get; set; }
    }
}
