//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureServer.CardReader
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblControllerConfig
    {
        public string ControlID { get; set; }
        public short ControlType { get; set; }
        public int ERID { get; set; }
        public string IP { get; set; }
        public int Port { get; set; }
        public string EntranceCode { get; set; }
        public string Loop { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
        public Nullable<double> ScaleX { get; set; }
        public Nullable<double> ScaleY { get; set; }
        public Nullable<double> Rotation { get; set; }
        public Nullable<int> PlaneID { get; set; }
        public Nullable<int> TriggerCCTVID { get; set; }
    }
}
