
//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace SecureServer
{

using System;
    using System.Collections.Generic;
    
public partial class tblItemConfig
{

    public tblItemConfig()
    {

        this.tblAIItem1HourLog = new HashSet<tblAIItem1HourLog>();

    }


    public int ItemID { get; set; }

    public string ItemName { get; set; }

    public Nullable<int> GroupID { get; set; }

    public string ControlID { get; set; }

    public string Type { get; set; }

    public string Lable { get; set; }

    public string Unit { get; set; }

    public Nullable<int> Degree { get; set; }

    public Nullable<double> WarningUpper { get; set; }

    public Nullable<double> WarningLower { get; set; }

    public Nullable<double> AlarmUpper { get; set; }

    public Nullable<double> AlarmLower { get; set; }

    public Nullable<double> Value { get; set; }

    public int Address { get; set; }

    public int BitNo { get; set; }

    public int Length { get; set; }

    public string Depiction { get; set; }

    public string AlarmMode { get; set; }

    public string AlarmContent { get; set; }

    public string AbnormalRecoveryContent { get; set; }

    public string AbnormalRecoveryMode { get; set; }

    public string UIType { get; set; }

    public double ValueScale { get; set; }

    public double Offset { get; set; }

    public double Coefficient { get; set; }

    public Nullable<int> DIInvokeWarningValue { get; set; }

    public bool IsShow { get; set; }

    public Nullable<double> ScaleX { get; set; }

    public Nullable<double> ScaleY { get; set; }

    public Nullable<double> Rotation { get; set; }

    public Nullable<double> X { get; set; }

    public Nullable<double> Y { get; set; }

    public string Lv0Color { get; set; }

    public string Lv1Color { get; set; }

    public string Lv2Color { get; set; }

    public Nullable<int> GroupTypeID { get; set; }

    public Nullable<int> KindID { get; set; }

    public Nullable<bool> Suppress { get; set; }



    public virtual tblControllerConfig tblControllerConfig { get; set; }

    public virtual tblItemGroup tblItemGroup { get; set; }

    public virtual ICollection<tblAIItem1HourLog> tblAIItem1HourLog { get; set; }

    public virtual tblItemGroupTypeInfo tblItemGroupTypeInfo { get; set; }

    public virtual tblItemKindInfo tblItemKindInfo { get; set; }

}

}
