
//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace SecureServer
{

using System;
    using System.Collections.Generic;
    
public partial class tblPowerMeter
{

    public int ERID { get; set; }

    public string ERName { get; set; }

    public string RTU_IP { get; set; }

    public int Port { get; set; }

    public Nullable<double> VA { get; set; }

    public Nullable<double> VB { get; set; }

    public Nullable<double> VC { get; set; }

    public Nullable<double> AVGV { get; set; }

    public Nullable<double> IA { get; set; }

    public Nullable<double> IB { get; set; }

    public Nullable<double> IC { get; set; }

    public Nullable<double> AVGI { get; set; }

    public Nullable<double> KW { get; set; }

    public Nullable<double> PF { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public string Memo { get; set; }

    public Nullable<double> CumulateValue { get; set; }

    public Nullable<double> InstantaneousValue { get; set; }

    public Nullable<double> PowerAlarmUpper { get; set; }

    public Nullable<double> PowerAlarmLower { get; set; }

    public Nullable<double> WaterAlarmUpper { get; set; }

    public Nullable<double> WaterAlarmLower { get; set; }

    public Nullable<bool> WaterAlarm { get; set; }

    public Nullable<bool> PowerAlarm { get; set; }

    public Nullable<double> WaterAlarmAvg { get; set; }

    public Nullable<double> PowerAlarmAvg { get; set; }

    public Nullable<double> WaterConsume { get; set; }

    public string WaterAlarmDesc { get; set; }

    public string PowerAlarmDesc { get; set; }

    public Nullable<double> KW24Avg { get; set; }

    public Nullable<double> kWh { get; set; }

    public Nullable<double> PowerConsume { get; set; }

    public Nullable<double> Power24Consume { get; set; }

    public Nullable<double> PowerAlarmBaseValue_LastYear { get; set; }

    public Nullable<double> PowerAlarmBaseValue_Yesterday { get; set; }

    public Nullable<double> PowerAlarmBaseValue_LastHour { get; set; }

    public Nullable<short> PowerAlarm_LastYear { get; set; }

    public Nullable<short> PowerAlarm_Yesterday { get; set; }

    public Nullable<short> PowerAlarm_LastHour { get; set; }

    public Nullable<double> Power1MonthDailyAvg { get; set; }

    public Nullable<double> Power2MonthDailyAvg { get; set; }

    public Nullable<double> Power3MonthDailyAvg { get; set; }

    public Nullable<double> Power4MonthDailyAvg { get; set; }

    public Nullable<double> Power5MonthDailyAvg { get; set; }

    public Nullable<double> Power6MonthDailyAvg { get; set; }

    public Nullable<double> Power7MonthDailyAvg { get; set; }

    public Nullable<double> Power8MonthDailyAvg { get; set; }

    public Nullable<double> Power9MonthDailyAvg { get; set; }

    public Nullable<double> Power10MonthDailyAvg { get; set; }

    public Nullable<double> Power11MonthDailyAvg { get; set; }

    public Nullable<double> Power12MonthDailyAvg { get; set; }

    public Nullable<double> SetThisPeriodkWh { get; set; }

    public Nullable<double> Water24Consume { get; set; }

    public Nullable<double> WaterAlarmBaseValue_LastYear { get; set; }

    public Nullable<short> WaterAlarm_LastYear { get; set; }

    public Nullable<double> Water1MonthDailyAvg { get; set; }

    public Nullable<double> Water2MonthDailyAvg { get; set; }

    public Nullable<double> Water3MonthDailyAvg { get; set; }

    public Nullable<double> Water4MonthDailyAvg { get; set; }

    public Nullable<double> Water5MonthDailyAvg { get; set; }

    public Nullable<double> Water6MonthDailyAvg { get; set; }

    public Nullable<double> Water7MonthDailyAvg { get; set; }

    public Nullable<double> Water8MonthDailyAvg { get; set; }

    public Nullable<double> Water9MonthDailyAvg { get; set; }

    public Nullable<double> Water10MonthDailyAvg { get; set; }

    public Nullable<double> Water11MonthDailyAvg { get; set; }

    public Nullable<double> Water12MonthDailyAvg { get; set; }

    public Nullable<double> SetThisPeriodWater { get; set; }

    public Nullable<double> CT { get; set; }

    public Nullable<double> SysThisPeriodWater { get; set; }

    public Nullable<double> SysThisPeriodPower { get; set; }

}

}
