
//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace SecureServer
{

using System;
    using System.Collections.Generic;
    
public partial class tblPowerMeter1HourLog
{

    public long FlowID { get; set; }

    public System.DateTime Timestamp { get; set; }

    public int ERID { get; set; }

    public Nullable<double> KW { get; set; }

    public Nullable<double> CumulateValue { get; set; }

    public string Memo { get; set; }

    public Nullable<double> WaterAlarmAvg { get; set; }

    public Nullable<double> PowerAlarmAvg { get; set; }

    public Nullable<bool> WaterAlarm { get; set; }

    public Nullable<bool> PowerAlarm { get; set; }

    public Nullable<double> WaterConsume { get; set; }

    public Nullable<double> KW24Avg { get; set; }

    public Nullable<double> Water24Consume { get; set; }

    public Nullable<double> WaterAlarmBaseValue_LastYear { get; set; }

    public Nullable<short> WaterAlarm_LastYear { get; set; }

    public Nullable<double> kWh { get; set; }

    public Nullable<double> PowerConsume { get; set; }

    public Nullable<double> Power24Consume { get; set; }

    public Nullable<double> PowerAlarmBaseValue_LastYear { get; set; }

    public Nullable<double> PowerAlarmBaseValue_Yesterday { get; set; }

    public Nullable<double> PowerAlarmBaseValue_LastHour { get; set; }

    public Nullable<short> PowerAlarm_LastYear { get; set; }

    public Nullable<short> PowerAlarm_Yesterday { get; set; }

    public Nullable<short> PowerAlarm_LastHour { get; set; }

}

}
