
//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace SecureServer
{

using System;
    using System.Collections.Generic;
    
public partial class vwAIImmediatelyCheck
{

    public string LineID { get; set; }

    public string ControlID { get; set; }

    public string LineName { get; set; }

    public string ERName { get; set; }

    public Nullable<decimal> TempValue { get; set; }

    public Nullable<decimal> RHValue { get; set; }

    public Nullable<decimal> DCValue { get; set; }

    public Nullable<decimal> OilValue { get; set; }

    public Nullable<decimal> Transmitter1Value { get; set; }

    public Nullable<decimal> Transmitter2Value { get; set; }

    public Nullable<decimal> Transmitter3Value { get; set; }

    public Nullable<decimal> Transmitter4Value { get; set; }

    public Nullable<decimal> Transmitter5Value { get; set; }

    public Nullable<decimal> Transmitter6Value { get; set; }

    public Nullable<decimal> Transmitter7Value { get; set; }

    public Nullable<decimal> Transmitter8Value { get; set; }

    public Nullable<decimal> Transmitter9Value { get; set; }

    public Nullable<decimal> Transmitter10Value { get; set; }

}

}
