
//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace SecureServer
{

using System;
    using System.Collections.Generic;
    
public partial class vwAlarmLog
{

    public long EventID { get; set; }

    public short TypeID { get; set; }

    public short TypeCode { get; set; }

    public System.DateTime Timestamp { get; set; }

    public string ControlID { get; set; }

    public Nullable<int> ItemID { get; set; }

    public string Value { get; set; }

    public string Memo { get; set; }

    public Nullable<int> ERID { get; set; }

    public string ERName { get; set; }

    public string ItemName { get; set; }

    public string Type { get; set; }

    public string Lable { get; set; }

    public string Unit { get; set; }

    public Nullable<int> Degree { get; set; }

    public Nullable<double> WarningUpper { get; set; }

    public Nullable<double> WarningLower { get; set; }

    public Nullable<double> AlarmUpper { get; set; }

    public Nullable<double> AlarmLower { get; set; }

    public string ItemConfig_Value { get; set; }

    public Nullable<int> Address { get; set; }

    public Nullable<int> BitNo { get; set; }

    public Nullable<int> Length { get; set; }

    public string Depiction { get; set; }

    public string AlarmMode { get; set; }

    public string AlarmContent { get; set; }

    public string AbnormalRecoveryContent { get; set; }

    public string AbnormalRecoveryMode { get; set; }

    public Nullable<int> DIInvokeWarningValue { get; set; }

    public Nullable<double> ValueScale { get; set; }

    public Nullable<double> Offset { get; set; }

    public Nullable<double> Coefficient { get; set; }

    public Nullable<bool> IsShow { get; set; }

    public string GroupName { get; set; }

    public Nullable<short> GroupType { get; set; }

    public string LineID { get; set; }

    public string LineName { get; set; }

    public string Explain { get; set; }

    public string TypeDetail_Memo { get; set; }

    public string GroupTypeName { get; set; }

    public string KindName { get; set; }

    public Nullable<bool> Suppress { get; set; }

}

}
