
//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace SecureServer
{

using System;
    using System.Collections.Generic;
    
public partial class vwItemConfig
{

    public int ItemID { get; set; }

    public string ItemName { get; set; }

    public Nullable<int> GroupID { get; set; }

    public string ControlID { get; set; }

    public string Type { get; set; }

    public string Lable { get; set; }

    public string Unit { get; set; }

    public Nullable<int> Degree { get; set; }

    public Nullable<double> WarningUpper { get; set; }

    public Nullable<double> WarningLower { get; set; }

    public Nullable<double> AlarmUpper { get; set; }

    public Nullable<double> AlarmLower { get; set; }

    public string Value { get; set; }

    public int Address { get; set; }

    public int BitNo { get; set; }

    public int Length { get; set; }

    public string Depiction { get; set; }

    public string AlarmMode { get; set; }

    public string AlarmContent { get; set; }

    public string AbnormalRecoveryContent { get; set; }

    public string AbnormalRecoveryMode { get; set; }

    public Nullable<int> DIInvokeWarningValue { get; set; }

    public string UIType { get; set; }

    public double ValueScale { get; set; }

    public double Offset { get; set; }

    public double Coefficient { get; set; }

    public bool IsShow { get; set; }

    public Nullable<double> ScaleX { get; set; }

    public Nullable<double> ScaleY { get; set; }

    public Nullable<double> Rotation { get; set; }

    public Nullable<double> X { get; set; }

    public Nullable<double> Y { get; set; }

    public Nullable<short> GroupType { get; set; }

    public string GroupName { get; set; }

    public Nullable<int> PlaneID { get; set; }

    public bool GroupIsShow { get; set; }

    public Nullable<int> ERID { get; set; }

    public string ERName { get; set; }

    public string PlaneName { get; set; }

    public string PictureDesc { get; set; }

    public Nullable<short> ControlType { get; set; }

    public string EntranceCode { get; set; }

    public string Loop { get; set; }

    public Nullable<bool> IsEnable { get; set; }

    public Nullable<int> TriggerCCTVID { get; set; }

    public Nullable<int> RTUBaseAddress { get; set; }

    public Nullable<int> RTURegisterLength { get; set; }

    public string LineID { get; set; }

    public string LineName { get; set; }

    public string Lv0ColorName { get; set; }

    public string Lv1ColorName { get; set; }

    public string Lv2ColorName { get; set; }

    public string Lv0Color { get; set; }

    public string Lv1Color { get; set; }

    public string Lv2Color { get; set; }

    public Nullable<int> GroupTypeID { get; set; }

    public string GroupTypeName { get; set; }

    public Nullable<int> KindID { get; set; }

    public string KindName { get; set; }

    public Nullable<bool> Suppress { get; set; }

    public string GroupNameDetail { get; set; }

}

}
