
//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace SecureServer
{

using System;
    using System.Collections.Generic;
    
public partial class vwPDAlarmLoopDeviceLog
{

    public long FlowID { get; set; }

    public System.DateTime Timestamp { get; set; }

    public Nullable<int> ERID { get; set; }

    public string ERName { get; set; }

    public string LineID { get; set; }

    public string Direction { get; set; }

    public Nullable<int> mile_m { get; set; }

    public string LineName { get; set; }

    public string DirectionName { get; set; }

    public string PDName { get; set; }

    public string PDItem { get; set; }

    public string PDItemDetail { get; set; }

    public int Loop { get; set; }

    public string Memo { get; set; }

    public Nullable<int> Status { get; set; }

    public string StatusDetail { get; set; }

    public string DeviceName { get; set; }

    public short PD_LoopNO { get; set; }

    public string Mapping_DeviceName { get; set; }

    public string Device_LineID { get; set; }

    public string Device_Direction { get; set; }

    public Nullable<int> Device_mile_m { get; set; }

    public string device_type { get; set; }

    public string Device_LineName { get; set; }

    public string Device_DirectionName { get; set; }

    public string PD_Mapping_DeviceName { get; set; }

    public string Classify { get; set; }

    public Nullable<int> WorkInfo { get; set; }

    public Nullable<double> Diameter { get; set; }

}

}
