//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomDoorControlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchConfig
    {
        public long SchID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string SchName { get; set; }
        public string SchDesc { get; set; }
        public Nullable<short> SchType { get; set; }
        public Nullable<bool> Week1 { get; set; }
        public Nullable<bool> Week2 { get; set; }
        public Nullable<bool> Week3 { get; set; }
        public Nullable<bool> Week4 { get; set; }
        public Nullable<bool> Week5 { get; set; }
        public Nullable<bool> Week6 { get; set; }
        public Nullable<bool> Week7 { get; set; }
        public string UserID { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<bool> Enable { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblSchLog tblSchLog { get; set; }
    }
}
