//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 關聯性中繼資料

[assembly: EdmRelationshipAttribute("SecureModel", "FK_tblGroupMenu_tblMenu", "tblMenu", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(slSecure.Web.tblMenu), "tblUserGroupMenu", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(slSecure.Web.tblUserGroupMenu), true)]
[assembly: EdmRelationshipAttribute("SecureModel", "FK_tblMenu_tblMenuGroup", "tblMenuGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(slSecure.Web.tblMenuGroup), "tblMenu", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(slSecure.Web.tblMenu), true)]
[assembly: EdmRelationshipAttribute("SecureModel", "FK_tblUser_tblUserGroup", "tblUserGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(slSecure.Web.tblUserGroup), "tblUser", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(slSecure.Web.tblUser), true)]
[assembly: EdmRelationshipAttribute("SecureModel", "FK_tblGroupMenu_tblUserGroup", "tblUserGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(slSecure.Web.tblUserGroup), "tblUserGroupMenu", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(slSecure.Web.tblUserGroupMenu), true)]

#endregion

namespace slSecure.Web
{
    #region 內容
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    public partial class SecureDB : ObjectContext
    {
        #region 建構函式
    
        /// <summary>
        /// 使用在應用程式組態檔的 'SecureDB' 區段中找到的連接字串，初始化新的 SecureDB 物件。
        /// </summary>
        public SecureDB() : base("name=SecureDB", "SecureDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 SecureDB 物件。
        /// </summary>
        public SecureDB(string connectionString) : base(connectionString, "SecureDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 SecureDB 物件。
        /// </summary>
        public SecureDB(EntityConnection connection) : base(connection, "SecureDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblMenu> tblMenu
        {
            get
            {
                if ((_tblMenu == null))
                {
                    _tblMenu = base.CreateObjectSet<tblMenu>("tblMenu");
                }
                return _tblMenu;
            }
        }
        private ObjectSet<tblMenu> _tblMenu;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblMenuGroup> tblMenuGroup
        {
            get
            {
                if ((_tblMenuGroup == null))
                {
                    _tblMenuGroup = base.CreateObjectSet<tblMenuGroup>("tblMenuGroup");
                }
                return _tblMenuGroup;
            }
        }
        private ObjectSet<tblMenuGroup> _tblMenuGroup;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblUser> tblUser
        {
            get
            {
                if ((_tblUser == null))
                {
                    _tblUser = base.CreateObjectSet<tblUser>("tblUser");
                }
                return _tblUser;
            }
        }
        private ObjectSet<tblUser> _tblUser;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblUserGroup> tblUserGroup
        {
            get
            {
                if ((_tblUserGroup == null))
                {
                    _tblUserGroup = base.CreateObjectSet<tblUserGroup>("tblUserGroup");
                }
                return _tblUserGroup;
            }
        }
        private ObjectSet<tblUserGroup> _tblUserGroup;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblUserGroupMenu> tblUserGroupMenu
        {
            get
            {
                if ((_tblUserGroupMenu == null))
                {
                    _tblUserGroupMenu = base.CreateObjectSet<tblUserGroupMenu>("tblUserGroupMenu");
                }
                return _tblUserGroupMenu;
            }
        }
        private ObjectSet<tblUserGroupMenu> _tblUserGroupMenu;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<vwUserMenuAllow> vwUserMenuAllow
        {
            get
            {
                if ((_vwUserMenuAllow == null))
                {
                    _vwUserMenuAllow = base.CreateObjectSet<vwUserMenuAllow>("vwUserMenuAllow");
                }
                return _vwUserMenuAllow;
            }
        }
        private ObjectSet<vwUserMenuAllow> _vwUserMenuAllow;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<vwUserGroupMenuAllow> vwUserGroupMenuAllow
        {
            get
            {
                if ((_vwUserGroupMenuAllow == null))
                {
                    _vwUserGroupMenuAllow = base.CreateObjectSet<vwUserGroupMenuAllow>("vwUserGroupMenuAllow");
                }
                return _vwUserGroupMenuAllow;
            }
        }
        private ObjectSet<vwUserGroupMenuAllow> _vwUserGroupMenuAllow;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 將新物件加入 tblMenu EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblMenu(tblMenu tblMenu)
        {
            base.AddObject("tblMenu", tblMenu);
        }
    
        /// <summary>
        /// 將新物件加入 tblMenuGroup EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblMenuGroup(tblMenuGroup tblMenuGroup)
        {
            base.AddObject("tblMenuGroup", tblMenuGroup);
        }
    
        /// <summary>
        /// 將新物件加入 tblUser EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblUser(tblUser tblUser)
        {
            base.AddObject("tblUser", tblUser);
        }
    
        /// <summary>
        /// 將新物件加入 tblUserGroup EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblUserGroup(tblUserGroup tblUserGroup)
        {
            base.AddObject("tblUserGroup", tblUserGroup);
        }
    
        /// <summary>
        /// 將新物件加入 tblUserGroupMenu EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblUserGroupMenu(tblUserGroupMenu tblUserGroupMenu)
        {
            base.AddObject("tblUserGroupMenu", tblUserGroupMenu);
        }
    
        /// <summary>
        /// 將新物件加入 vwUserMenuAllow EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTovwUserMenuAllow(vwUserMenuAllow vwUserMenuAllow)
        {
            base.AddObject("vwUserMenuAllow", vwUserMenuAllow);
        }
    
        /// <summary>
        /// 將新物件加入 vwUserGroupMenuAllow EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTovwUserGroupMenuAllow(vwUserGroupMenuAllow vwUserGroupMenuAllow)
        {
            base.AddObject("vwUserGroupMenuAllow", vwUserGroupMenuAllow);
        }

        #endregion

    }

    #endregion

    #region 實體
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SecureModel", Name="tblMenu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblMenu : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblMenu 物件。
        /// </summary>
        /// <param name="menuID">MenuID 屬性的初始值。</param>
        /// <param name="menuGroupID">MenuGroupID 屬性的初始值。</param>
        /// <param name="menuName">MenuName 屬性的初始值。</param>
        /// <param name="xAML">XAML 屬性的初始值。</param>
        public static tblMenu CreatetblMenu(global::System.Int32 menuID, global::System.Int32 menuGroupID, global::System.String menuName, global::System.String xAML)
        {
            tblMenu tblMenu = new tblMenu();
            tblMenu.MenuID = menuID;
            tblMenu.MenuGroupID = menuGroupID;
            tblMenu.MenuName = menuName;
            tblMenu.XAML = xAML;
            return tblMenu;
        }

        #endregion

        #region 簡單屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MenuID
        {
            get
            {
                return _MenuID;
            }
            set
            {
                if (_MenuID != value)
                {
                    OnMenuIDChanging(value);
                    ReportPropertyChanging("MenuID");
                    _MenuID = StructuralObject.SetValidValue(value, "MenuID");
                    ReportPropertyChanged("MenuID");
                    OnMenuIDChanged();
                }
            }
        }
        private global::System.Int32 _MenuID;
        partial void OnMenuIDChanging(global::System.Int32 value);
        partial void OnMenuIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MenuGroupID
        {
            get
            {
                return _MenuGroupID;
            }
            set
            {
                OnMenuGroupIDChanging(value);
                ReportPropertyChanging("MenuGroupID");
                _MenuGroupID = StructuralObject.SetValidValue(value, "MenuGroupID");
                ReportPropertyChanged("MenuGroupID");
                OnMenuGroupIDChanged();
            }
        }
        private global::System.Int32 _MenuGroupID;
        partial void OnMenuGroupIDChanging(global::System.Int32 value);
        partial void OnMenuGroupIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MenuName
        {
            get
            {
                return _MenuName;
            }
            set
            {
                OnMenuNameChanging(value);
                ReportPropertyChanging("MenuName");
                _MenuName = StructuralObject.SetValidValue(value, false, "MenuName");
                ReportPropertyChanged("MenuName");
                OnMenuNameChanged();
            }
        }
        private global::System.String _MenuName;
        partial void OnMenuNameChanging(global::System.String value);
        partial void OnMenuNameChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String XAML
        {
            get
            {
                return _XAML;
            }
            set
            {
                OnXAMLChanging(value);
                ReportPropertyChanging("XAML");
                _XAML = StructuralObject.SetValidValue(value, false, "XAML");
                ReportPropertyChanged("XAML");
                OnXAMLChanged();
            }
        }
        private global::System.String _XAML;
        partial void OnXAMLChanging(global::System.String value);
        partial void OnXAMLChanged();

        #endregion

        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SecureModel", "FK_tblGroupMenu_tblMenu", "tblUserGroupMenu")]
        public EntityCollection<tblUserGroupMenu> tblUserGroupMenu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblUserGroupMenu>("SecureModel.FK_tblGroupMenu_tblMenu", "tblUserGroupMenu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblUserGroupMenu>("SecureModel.FK_tblGroupMenu_tblMenu", "tblUserGroupMenu", value);
                }
            }
        }
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SecureModel", "FK_tblMenu_tblMenuGroup", "tblMenuGroup")]
        public tblMenuGroup tblMenuGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMenuGroup>("SecureModel.FK_tblMenu_tblMenuGroup", "tblMenuGroup").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMenuGroup>("SecureModel.FK_tblMenu_tblMenuGroup", "tblMenuGroup").Value = value;
            }
        }
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblMenuGroup> tblMenuGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMenuGroup>("SecureModel.FK_tblMenu_tblMenuGroup", "tblMenuGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblMenuGroup>("SecureModel.FK_tblMenu_tblMenuGroup", "tblMenuGroup", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SecureModel", Name="tblMenuGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblMenuGroup : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblMenuGroup 物件。
        /// </summary>
        /// <param name="menuGroupID">MenuGroupID 屬性的初始值。</param>
        /// <param name="groupName">GroupName 屬性的初始值。</param>
        public static tblMenuGroup CreatetblMenuGroup(global::System.Int32 menuGroupID, global::System.String groupName)
        {
            tblMenuGroup tblMenuGroup = new tblMenuGroup();
            tblMenuGroup.MenuGroupID = menuGroupID;
            tblMenuGroup.GroupName = groupName;
            return tblMenuGroup;
        }

        #endregion

        #region 簡單屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MenuGroupID
        {
            get
            {
                return _MenuGroupID;
            }
            set
            {
                if (_MenuGroupID != value)
                {
                    OnMenuGroupIDChanging(value);
                    ReportPropertyChanging("MenuGroupID");
                    _MenuGroupID = StructuralObject.SetValidValue(value, "MenuGroupID");
                    ReportPropertyChanged("MenuGroupID");
                    OnMenuGroupIDChanged();
                }
            }
        }
        private global::System.Int32 _MenuGroupID;
        partial void OnMenuGroupIDChanging(global::System.Int32 value);
        partial void OnMenuGroupIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GroupName
        {
            get
            {
                return _GroupName;
            }
            set
            {
                OnGroupNameChanging(value);
                ReportPropertyChanging("GroupName");
                _GroupName = StructuralObject.SetValidValue(value, false, "GroupName");
                ReportPropertyChanged("GroupName");
                OnGroupNameChanged();
            }
        }
        private global::System.String _GroupName;
        partial void OnGroupNameChanging(global::System.String value);
        partial void OnGroupNameChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MenuOrder
        {
            get
            {
                return _MenuOrder;
            }
            set
            {
                OnMenuOrderChanging(value);
                ReportPropertyChanging("MenuOrder");
                _MenuOrder = StructuralObject.SetValidValue(value, "MenuOrder");
                ReportPropertyChanged("MenuOrder");
                OnMenuOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _MenuOrder;
        partial void OnMenuOrderChanging(Nullable<global::System.Int32> value);
        partial void OnMenuOrderChanged();

        #endregion

        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SecureModel", "FK_tblMenu_tblMenuGroup", "tblMenu")]
        public EntityCollection<tblMenu> tblMenu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblMenu>("SecureModel.FK_tblMenu_tblMenuGroup", "tblMenu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblMenu>("SecureModel.FK_tblMenu_tblMenuGroup", "tblMenu", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SecureModel", Name="tblUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUser : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblUser 物件。
        /// </summary>
        /// <param name="userID">UserID 屬性的初始值。</param>
        /// <param name="password">Password 屬性的初始值。</param>
        /// <param name="groupID">GroupID 屬性的初始值。</param>
        public static tblUser CreatetblUser(global::System.String userID, global::System.String password, global::System.Int32 groupID)
        {
            tblUser tblUser = new tblUser();
            tblUser.UserID = userID;
            tblUser.Password = password;
            tblUser.GroupID = groupID;
            return tblUser;
        }

        #endregion

        #region 簡單屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value, false, "UserID");
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.String _UserID;
        partial void OnUserIDChanging(global::System.String value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                OnGroupIDChanging(value);
                ReportPropertyChanging("GroupID");
                _GroupID = StructuralObject.SetValidValue(value, "GroupID");
                ReportPropertyChanged("GroupID");
                OnGroupIDChanged();
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true, "UserName");
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();

        #endregion

        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SecureModel", "FK_tblUser_tblUserGroup", "tblUserGroup")]
        public tblUserGroup tblUserGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUserGroup>("SecureModel.FK_tblUser_tblUserGroup", "tblUserGroup").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUserGroup>("SecureModel.FK_tblUser_tblUserGroup", "tblUserGroup").Value = value;
            }
        }
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblUserGroup> tblUserGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUserGroup>("SecureModel.FK_tblUser_tblUserGroup", "tblUserGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblUserGroup>("SecureModel.FK_tblUser_tblUserGroup", "tblUserGroup", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SecureModel", Name="tblUserGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUserGroup : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblUserGroup 物件。
        /// </summary>
        /// <param name="groupID">GroupID 屬性的初始值。</param>
        /// <param name="groupName">GroupName 屬性的初始值。</param>
        public static tblUserGroup CreatetblUserGroup(global::System.Int32 groupID, global::System.String groupName)
        {
            tblUserGroup tblUserGroup = new tblUserGroup();
            tblUserGroup.GroupID = groupID;
            tblUserGroup.GroupName = groupName;
            return tblUserGroup;
        }

        #endregion

        #region 簡單屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                if (_GroupID != value)
                {
                    OnGroupIDChanging(value);
                    ReportPropertyChanging("GroupID");
                    _GroupID = StructuralObject.SetValidValue(value, "GroupID");
                    ReportPropertyChanged("GroupID");
                    OnGroupIDChanged();
                }
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GroupName
        {
            get
            {
                return _GroupName;
            }
            set
            {
                OnGroupNameChanging(value);
                ReportPropertyChanging("GroupName");
                _GroupName = StructuralObject.SetValidValue(value, false, "GroupName");
                ReportPropertyChanged("GroupName");
                OnGroupNameChanged();
            }
        }
        private global::System.String _GroupName;
        partial void OnGroupNameChanging(global::System.String value);
        partial void OnGroupNameChanged();

        #endregion

        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SecureModel", "FK_tblUser_tblUserGroup", "tblUser")]
        public EntityCollection<tblUser> tblUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblUser>("SecureModel.FK_tblUser_tblUserGroup", "tblUser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblUser>("SecureModel.FK_tblUser_tblUserGroup", "tblUser", value);
                }
            }
        }
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SecureModel", "FK_tblGroupMenu_tblUserGroup", "tblUserGroupMenu")]
        public EntityCollection<tblUserGroupMenu> tblUserGroupMenu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblUserGroupMenu>("SecureModel.FK_tblGroupMenu_tblUserGroup", "tblUserGroupMenu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblUserGroupMenu>("SecureModel.FK_tblGroupMenu_tblUserGroup", "tblUserGroupMenu", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SecureModel", Name="tblUserGroupMenu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUserGroupMenu : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblUserGroupMenu 物件。
        /// </summary>
        /// <param name="groupID">GroupID 屬性的初始值。</param>
        /// <param name="menuID">MenuID 屬性的初始值。</param>
        /// <param name="isAllow">IsAllow 屬性的初始值。</param>
        public static tblUserGroupMenu CreatetblUserGroupMenu(global::System.Int32 groupID, global::System.Int32 menuID, global::System.Boolean isAllow)
        {
            tblUserGroupMenu tblUserGroupMenu = new tblUserGroupMenu();
            tblUserGroupMenu.GroupID = groupID;
            tblUserGroupMenu.MenuID = menuID;
            tblUserGroupMenu.IsAllow = isAllow;
            return tblUserGroupMenu;
        }

        #endregion

        #region 簡單屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                if (_GroupID != value)
                {
                    OnGroupIDChanging(value);
                    ReportPropertyChanging("GroupID");
                    _GroupID = StructuralObject.SetValidValue(value, "GroupID");
                    ReportPropertyChanged("GroupID");
                    OnGroupIDChanged();
                }
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MenuID
        {
            get
            {
                return _MenuID;
            }
            set
            {
                if (_MenuID != value)
                {
                    OnMenuIDChanging(value);
                    ReportPropertyChanging("MenuID");
                    _MenuID = StructuralObject.SetValidValue(value, "MenuID");
                    ReportPropertyChanged("MenuID");
                    OnMenuIDChanged();
                }
            }
        }
        private global::System.Int32 _MenuID;
        partial void OnMenuIDChanging(global::System.Int32 value);
        partial void OnMenuIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAllow
        {
            get
            {
                return _IsAllow;
            }
            set
            {
                OnIsAllowChanging(value);
                ReportPropertyChanging("IsAllow");
                _IsAllow = StructuralObject.SetValidValue(value, "IsAllow");
                ReportPropertyChanged("IsAllow");
                OnIsAllowChanged();
            }
        }
        private global::System.Boolean _IsAllow;
        partial void OnIsAllowChanging(global::System.Boolean value);
        partial void OnIsAllowChanged();

        #endregion

        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SecureModel", "FK_tblGroupMenu_tblMenu", "tblMenu")]
        public tblMenu tblMenu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMenu>("SecureModel.FK_tblGroupMenu_tblMenu", "tblMenu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMenu>("SecureModel.FK_tblGroupMenu_tblMenu", "tblMenu").Value = value;
            }
        }
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblMenu> tblMenuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMenu>("SecureModel.FK_tblGroupMenu_tblMenu", "tblMenu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblMenu>("SecureModel.FK_tblGroupMenu_tblMenu", "tblMenu", value);
                }
            }
        }
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SecureModel", "FK_tblGroupMenu_tblUserGroup", "tblUserGroup")]
        public tblUserGroup tblUserGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUserGroup>("SecureModel.FK_tblGroupMenu_tblUserGroup", "tblUserGroup").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUserGroup>("SecureModel.FK_tblGroupMenu_tblUserGroup", "tblUserGroup").Value = value;
            }
        }
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblUserGroup> tblUserGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUserGroup>("SecureModel.FK_tblGroupMenu_tblUserGroup", "tblUserGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblUserGroup>("SecureModel.FK_tblGroupMenu_tblUserGroup", "tblUserGroup", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SecureModel", Name="vwUserGroupMenuAllow")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwUserGroupMenuAllow : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 vwUserGroupMenuAllow 物件。
        /// </summary>
        /// <param name="groupID">GroupID 屬性的初始值。</param>
        /// <param name="groupName">GroupName 屬性的初始值。</param>
        /// <param name="isAllow">IsAllow 屬性的初始值。</param>
        /// <param name="menuID">MenuID 屬性的初始值。</param>
        /// <param name="menuName">MenuName 屬性的初始值。</param>
        public static vwUserGroupMenuAllow CreatevwUserGroupMenuAllow(global::System.Int32 groupID, global::System.String groupName, global::System.Boolean isAllow, global::System.Int32 menuID, global::System.String menuName)
        {
            vwUserGroupMenuAllow vwUserGroupMenuAllow = new vwUserGroupMenuAllow();
            vwUserGroupMenuAllow.GroupID = groupID;
            vwUserGroupMenuAllow.GroupName = groupName;
            vwUserGroupMenuAllow.IsAllow = isAllow;
            vwUserGroupMenuAllow.MenuID = menuID;
            vwUserGroupMenuAllow.MenuName = menuName;
            return vwUserGroupMenuAllow;
        }

        #endregion

        #region 簡單屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                if (_GroupID != value)
                {
                    OnGroupIDChanging(value);
                    ReportPropertyChanging("GroupID");
                    _GroupID = StructuralObject.SetValidValue(value, "GroupID");
                    ReportPropertyChanged("GroupID");
                    OnGroupIDChanged();
                }
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GroupName
        {
            get
            {
                return _GroupName;
            }
            set
            {
                if (_GroupName != value)
                {
                    OnGroupNameChanging(value);
                    ReportPropertyChanging("GroupName");
                    _GroupName = StructuralObject.SetValidValue(value, false, "GroupName");
                    ReportPropertyChanged("GroupName");
                    OnGroupNameChanged();
                }
            }
        }
        private global::System.String _GroupName;
        partial void OnGroupNameChanging(global::System.String value);
        partial void OnGroupNameChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAllow
        {
            get
            {
                return _IsAllow;
            }
            set
            {
                if (_IsAllow != value)
                {
                    OnIsAllowChanging(value);
                    ReportPropertyChanging("IsAllow");
                    _IsAllow = StructuralObject.SetValidValue(value, "IsAllow");
                    ReportPropertyChanged("IsAllow");
                    OnIsAllowChanged();
                }
            }
        }
        private global::System.Boolean _IsAllow;
        partial void OnIsAllowChanging(global::System.Boolean value);
        partial void OnIsAllowChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MenuID
        {
            get
            {
                return _MenuID;
            }
            set
            {
                if (_MenuID != value)
                {
                    OnMenuIDChanging(value);
                    ReportPropertyChanging("MenuID");
                    _MenuID = StructuralObject.SetValidValue(value, "MenuID");
                    ReportPropertyChanged("MenuID");
                    OnMenuIDChanged();
                }
            }
        }
        private global::System.Int32 _MenuID;
        partial void OnMenuIDChanging(global::System.Int32 value);
        partial void OnMenuIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MenuName
        {
            get
            {
                return _MenuName;
            }
            set
            {
                if (_MenuName != value)
                {
                    OnMenuNameChanging(value);
                    ReportPropertyChanging("MenuName");
                    _MenuName = StructuralObject.SetValidValue(value, false, "MenuName");
                    ReportPropertyChanged("MenuName");
                    OnMenuNameChanged();
                }
            }
        }
        private global::System.String _MenuName;
        partial void OnMenuNameChanging(global::System.String value);
        partial void OnMenuNameChanged();

        #endregion

    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SecureModel", Name="vwUserMenuAllow")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwUserMenuAllow : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 vwUserMenuAllow 物件。
        /// </summary>
        /// <param name="groupID">GroupID 屬性的初始值。</param>
        /// <param name="menuID">MenuID 屬性的初始值。</param>
        /// <param name="isAllow">IsAllow 屬性的初始值。</param>
        /// <param name="menuName">MenuName 屬性的初始值。</param>
        /// <param name="menuGroupID">MenuGroupID 屬性的初始值。</param>
        /// <param name="xAML">XAML 屬性的初始值。</param>
        /// <param name="groupName">GroupName 屬性的初始值。</param>
        /// <param name="userID">UserID 屬性的初始值。</param>
        public static vwUserMenuAllow CreatevwUserMenuAllow(global::System.Int32 groupID, global::System.Int32 menuID, global::System.Boolean isAllow, global::System.String menuName, global::System.Int32 menuGroupID, global::System.String xAML, global::System.String groupName, global::System.String userID)
        {
            vwUserMenuAllow vwUserMenuAllow = new vwUserMenuAllow();
            vwUserMenuAllow.GroupID = groupID;
            vwUserMenuAllow.MenuID = menuID;
            vwUserMenuAllow.IsAllow = isAllow;
            vwUserMenuAllow.MenuName = menuName;
            vwUserMenuAllow.MenuGroupID = menuGroupID;
            vwUserMenuAllow.XAML = xAML;
            vwUserMenuAllow.GroupName = groupName;
            vwUserMenuAllow.UserID = userID;
            return vwUserMenuAllow;
        }

        #endregion

        #region 簡單屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                if (_GroupID != value)
                {
                    OnGroupIDChanging(value);
                    ReportPropertyChanging("GroupID");
                    _GroupID = StructuralObject.SetValidValue(value, "GroupID");
                    ReportPropertyChanged("GroupID");
                    OnGroupIDChanged();
                }
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MenuID
        {
            get
            {
                return _MenuID;
            }
            set
            {
                if (_MenuID != value)
                {
                    OnMenuIDChanging(value);
                    ReportPropertyChanging("MenuID");
                    _MenuID = StructuralObject.SetValidValue(value, "MenuID");
                    ReportPropertyChanged("MenuID");
                    OnMenuIDChanged();
                }
            }
        }
        private global::System.Int32 _MenuID;
        partial void OnMenuIDChanging(global::System.Int32 value);
        partial void OnMenuIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAllow
        {
            get
            {
                return _IsAllow;
            }
            set
            {
                if (_IsAllow != value)
                {
                    OnIsAllowChanging(value);
                    ReportPropertyChanging("IsAllow");
                    _IsAllow = StructuralObject.SetValidValue(value, "IsAllow");
                    ReportPropertyChanged("IsAllow");
                    OnIsAllowChanged();
                }
            }
        }
        private global::System.Boolean _IsAllow;
        partial void OnIsAllowChanging(global::System.Boolean value);
        partial void OnIsAllowChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MenuName
        {
            get
            {
                return _MenuName;
            }
            set
            {
                if (_MenuName != value)
                {
                    OnMenuNameChanging(value);
                    ReportPropertyChanging("MenuName");
                    _MenuName = StructuralObject.SetValidValue(value, false, "MenuName");
                    ReportPropertyChanged("MenuName");
                    OnMenuNameChanged();
                }
            }
        }
        private global::System.String _MenuName;
        partial void OnMenuNameChanging(global::System.String value);
        partial void OnMenuNameChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MenuGroupID
        {
            get
            {
                return _MenuGroupID;
            }
            set
            {
                if (_MenuGroupID != value)
                {
                    OnMenuGroupIDChanging(value);
                    ReportPropertyChanging("MenuGroupID");
                    _MenuGroupID = StructuralObject.SetValidValue(value, "MenuGroupID");
                    ReportPropertyChanged("MenuGroupID");
                    OnMenuGroupIDChanged();
                }
            }
        }
        private global::System.Int32 _MenuGroupID;
        partial void OnMenuGroupIDChanging(global::System.Int32 value);
        partial void OnMenuGroupIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String XAML
        {
            get
            {
                return _XAML;
            }
            set
            {
                if (_XAML != value)
                {
                    OnXAMLChanging(value);
                    ReportPropertyChanging("XAML");
                    _XAML = StructuralObject.SetValidValue(value, false, "XAML");
                    ReportPropertyChanged("XAML");
                    OnXAMLChanged();
                }
            }
        }
        private global::System.String _XAML;
        partial void OnXAMLChanging(global::System.String value);
        partial void OnXAMLChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GroupName
        {
            get
            {
                return _GroupName;
            }
            set
            {
                if (_GroupName != value)
                {
                    OnGroupNameChanging(value);
                    ReportPropertyChanging("GroupName");
                    _GroupName = StructuralObject.SetValidValue(value, false, "GroupName");
                    ReportPropertyChanged("GroupName");
                    OnGroupNameChanged();
                }
            }
        }
        private global::System.String _GroupName;
        partial void OnGroupNameChanging(global::System.String value);
        partial void OnGroupNameChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value, false, "UserID");
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.String _UserID;
        partial void OnUserIDChanging(global::System.String value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MenuOrder
        {
            get
            {
                return _MenuOrder;
            }
            set
            {
                OnMenuOrderChanging(value);
                ReportPropertyChanging("MenuOrder");
                _MenuOrder = StructuralObject.SetValidValue(value, "MenuOrder");
                ReportPropertyChanged("MenuOrder");
                OnMenuOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _MenuOrder;
        partial void OnMenuOrderChanging(Nullable<global::System.Int32> value);
        partial void OnMenuOrderChanged();

        #endregion

    }

    #endregion

}
