//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.MCNSService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RoomInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ERIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LineIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ERID {
            get {
                return this.ERIDField;
            }
            set {
                if ((this.ERIDField.Equals(value) != true)) {
                    this.ERIDField = value;
                    this.RaisePropertyChanged("ERID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ERName {
            get {
                return this.ERNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ERNameField, value) != true)) {
                    this.ERNameField = value;
                    this.RaisePropertyChanged("ERName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LineID {
            get {
                return this.LineIDField;
            }
            set {
                if ((object.ReferenceEquals(this.LineIDField, value) != true)) {
                    this.LineIDField = value;
                    this.RaisePropertyChanged("LineID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddCardInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AddCardInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MCNSIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test.MCNSService.ArrayOfInt ERIDsField;
        
        private System.DateTime StartDateField;
        
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MCNSID {
            get {
                return this.MCNSIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MCNSIDField, value) != true)) {
                    this.MCNSIDField = value;
                    this.RaisePropertyChanged("MCNSID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CardNo {
            get {
                return this.CardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNoField, value) != true)) {
                    this.CardNoField = value;
                    this.RaisePropertyChanged("CardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public test.MCNSService.ArrayOfInt ERIDs {
            get {
                return this.ERIDsField;
            }
            set {
                if ((object.ReferenceEquals(this.ERIDsField, value) != true)) {
                    this.ERIDsField = value;
                    this.RaisePropertyChanged("ERIDs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MagneticCardBasicInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MagneticCardBasicInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ABAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        private System.Nullable<System.DateTime> CardStartDateField;
        
        private System.Nullable<System.DateTime> CardEndDateField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        private System.Nullable<System.DateTime> EndDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ABA {
            get {
                return this.ABAField;
            }
            set {
                if ((object.ReferenceEquals(this.ABAField, value) != true)) {
                    this.ABAField = value;
                    this.RaisePropertyChanged("ABA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IDNumber {
            get {
                return this.IDNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IDNumberField, value) != true)) {
                    this.IDNumberField = value;
                    this.RaisePropertyChanged("IDNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EmployeeNo {
            get {
                return this.EmployeeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNoField, value) != true)) {
                    this.EmployeeNoField = value;
                    this.RaisePropertyChanged("EmployeeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string JobTitle {
            get {
                return this.JobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTitleField, value) != true)) {
                    this.JobTitleField = value;
                    this.RaisePropertyChanged("JobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Tel {
            get {
                return this.TelField;
            }
            set {
                if ((object.ReferenceEquals(this.TelField, value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<System.DateTime> CardStartDate {
            get {
                return this.CardStartDateField;
            }
            set {
                if ((this.CardStartDateField.Equals(value) != true)) {
                    this.CardStartDateField = value;
                    this.RaisePropertyChanged("CardStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<System.DateTime> CardEndDate {
            get {
                return this.CardEndDateField;
            }
            set {
                if ((this.CardEndDateField.Equals(value) != true)) {
                    this.CardEndDateField = value;
                    this.RaisePropertyChanged("CardEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MCNSService.MCNSServiceSoap")]
    public interface MCNSServiceSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  HelloWorldResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        test.MCNSService.HelloWorldResponse HelloWorld(test.MCNSService.HelloWorldRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  GetAllRoomResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllRoom", ReplyAction="*")]
        test.MCNSService.GetAllRoomResponse GetAllRoom(test.MCNSService.GetAllRoomRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  MCNSID 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCardInfoByMCNSID", ReplyAction="*")]
        test.MCNSService.GetCardInfoByMCNSIDResponse GetCardInfoByMCNSID(test.MCNSService.GetCardInfoByMCNSIDRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  GetAllTempMagneticCardBasicInfoResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTempMagneticCardBasicInfo", ReplyAction="*")]
        test.MCNSService.GetAllTempMagneticCardBasicInfoResponse GetAllTempMagneticCardBasicInfo(test.MCNSService.GetAllTempMagneticCardBasicInfoRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  CompanyName 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMagneticCardBasicInfoByCompany", ReplyAction="*")]
        test.MCNSService.GetMagneticCardBasicInfoByCompanyResponse GetMagneticCardBasicInfoByCompany(test.MCNSService.GetMagneticCardBasicInfoByCompanyRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  info 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCard", ReplyAction="*")]
        test.MCNSService.AddCardResponse AddCard(test.MCNSService.AddCardRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public test.MCNSService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(test.MCNSService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.MCNSService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(test.MCNSService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRoom", Namespace="http://tempuri.org/", Order=0)]
        public test.MCNSService.GetAllRoomRequestBody Body;
        
        public GetAllRoomRequest() {
        }
        
        public GetAllRoomRequest(test.MCNSService.GetAllRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRoomRequestBody {
        
        public GetAllRoomRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRoomResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.MCNSService.GetAllRoomResponseBody Body;
        
        public GetAllRoomResponse() {
        }
        
        public GetAllRoomResponse(test.MCNSService.GetAllRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllRoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public test.MCNSService.RoomInfo[] GetAllRoomResult;
        
        public GetAllRoomResponseBody() {
        }
        
        public GetAllRoomResponseBody(test.MCNSService.RoomInfo[] GetAllRoomResult) {
            this.GetAllRoomResult = GetAllRoomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCardInfoByMCNSIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCardInfoByMCNSID", Namespace="http://tempuri.org/", Order=0)]
        public test.MCNSService.GetCardInfoByMCNSIDRequestBody Body;
        
        public GetCardInfoByMCNSIDRequest() {
        }
        
        public GetCardInfoByMCNSIDRequest(test.MCNSService.GetCardInfoByMCNSIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCardInfoByMCNSIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MCNSID;
        
        public GetCardInfoByMCNSIDRequestBody() {
        }
        
        public GetCardInfoByMCNSIDRequestBody(string MCNSID) {
            this.MCNSID = MCNSID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCardInfoByMCNSIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCardInfoByMCNSIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.MCNSService.GetCardInfoByMCNSIDResponseBody Body;
        
        public GetCardInfoByMCNSIDResponse() {
        }
        
        public GetCardInfoByMCNSIDResponse(test.MCNSService.GetCardInfoByMCNSIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCardInfoByMCNSIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public test.MCNSService.AddCardInfo[] GetCardInfoByMCNSIDResult;
        
        public GetCardInfoByMCNSIDResponseBody() {
        }
        
        public GetCardInfoByMCNSIDResponseBody(test.MCNSService.AddCardInfo[] GetCardInfoByMCNSIDResult) {
            this.GetCardInfoByMCNSIDResult = GetCardInfoByMCNSIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTempMagneticCardBasicInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTempMagneticCardBasicInfo", Namespace="http://tempuri.org/", Order=0)]
        public test.MCNSService.GetAllTempMagneticCardBasicInfoRequestBody Body;
        
        public GetAllTempMagneticCardBasicInfoRequest() {
        }
        
        public GetAllTempMagneticCardBasicInfoRequest(test.MCNSService.GetAllTempMagneticCardBasicInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllTempMagneticCardBasicInfoRequestBody {
        
        public GetAllTempMagneticCardBasicInfoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTempMagneticCardBasicInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTempMagneticCardBasicInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.MCNSService.GetAllTempMagneticCardBasicInfoResponseBody Body;
        
        public GetAllTempMagneticCardBasicInfoResponse() {
        }
        
        public GetAllTempMagneticCardBasicInfoResponse(test.MCNSService.GetAllTempMagneticCardBasicInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTempMagneticCardBasicInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public test.MCNSService.MagneticCardBasicInfo[] GetAllTempMagneticCardBasicInfoResult;
        
        public GetAllTempMagneticCardBasicInfoResponseBody() {
        }
        
        public GetAllTempMagneticCardBasicInfoResponseBody(test.MCNSService.MagneticCardBasicInfo[] GetAllTempMagneticCardBasicInfoResult) {
            this.GetAllTempMagneticCardBasicInfoResult = GetAllTempMagneticCardBasicInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMagneticCardBasicInfoByCompanyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMagneticCardBasicInfoByCompany", Namespace="http://tempuri.org/", Order=0)]
        public test.MCNSService.GetMagneticCardBasicInfoByCompanyRequestBody Body;
        
        public GetMagneticCardBasicInfoByCompanyRequest() {
        }
        
        public GetMagneticCardBasicInfoByCompanyRequest(test.MCNSService.GetMagneticCardBasicInfoByCompanyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMagneticCardBasicInfoByCompanyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CompanyName;
        
        public GetMagneticCardBasicInfoByCompanyRequestBody() {
        }
        
        public GetMagneticCardBasicInfoByCompanyRequestBody(string CompanyName) {
            this.CompanyName = CompanyName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMagneticCardBasicInfoByCompanyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMagneticCardBasicInfoByCompanyResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.MCNSService.GetMagneticCardBasicInfoByCompanyResponseBody Body;
        
        public GetMagneticCardBasicInfoByCompanyResponse() {
        }
        
        public GetMagneticCardBasicInfoByCompanyResponse(test.MCNSService.GetMagneticCardBasicInfoByCompanyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMagneticCardBasicInfoByCompanyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public test.MCNSService.MagneticCardBasicInfo[] GetMagneticCardBasicInfoByCompanyResult;
        
        public GetMagneticCardBasicInfoByCompanyResponseBody() {
        }
        
        public GetMagneticCardBasicInfoByCompanyResponseBody(test.MCNSService.MagneticCardBasicInfo[] GetMagneticCardBasicInfoByCompanyResult) {
            this.GetMagneticCardBasicInfoByCompanyResult = GetMagneticCardBasicInfoByCompanyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCard", Namespace="http://tempuri.org/", Order=0)]
        public test.MCNSService.AddCardRequestBody Body;
        
        public AddCardRequest() {
        }
        
        public AddCardRequest(test.MCNSService.AddCardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCardRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public test.MCNSService.AddCardInfo info;
        
        public AddCardRequestBody() {
        }
        
        public AddCardRequestBody(test.MCNSService.AddCardInfo info) {
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCardResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.MCNSService.AddCardResponseBody Body;
        
        public AddCardResponse() {
        }
        
        public AddCardResponse(test.MCNSService.AddCardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCardResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddCardResult;
        
        public AddCardResponseBody() {
        }
        
        public AddCardResponseBody(string AddCardResult) {
            this.AddCardResult = AddCardResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MCNSServiceSoapChannel : test.MCNSService.MCNSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MCNSServiceSoapClient : System.ServiceModel.ClientBase<test.MCNSService.MCNSServiceSoap>, test.MCNSService.MCNSServiceSoap {
        
        public MCNSServiceSoapClient() {
        }
        
        public MCNSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MCNSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MCNSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MCNSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.MCNSService.HelloWorldResponse test.MCNSService.MCNSServiceSoap.HelloWorld(test.MCNSService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            test.MCNSService.HelloWorldRequest inValue = new test.MCNSService.HelloWorldRequest();
            inValue.Body = new test.MCNSService.HelloWorldRequestBody();
            test.MCNSService.HelloWorldResponse retVal = ((test.MCNSService.MCNSServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.MCNSService.GetAllRoomResponse test.MCNSService.MCNSServiceSoap.GetAllRoom(test.MCNSService.GetAllRoomRequest request) {
            return base.Channel.GetAllRoom(request);
        }
        
        public test.MCNSService.RoomInfo[] GetAllRoom() {
            test.MCNSService.GetAllRoomRequest inValue = new test.MCNSService.GetAllRoomRequest();
            inValue.Body = new test.MCNSService.GetAllRoomRequestBody();
            test.MCNSService.GetAllRoomResponse retVal = ((test.MCNSService.MCNSServiceSoap)(this)).GetAllRoom(inValue);
            return retVal.Body.GetAllRoomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.MCNSService.GetCardInfoByMCNSIDResponse test.MCNSService.MCNSServiceSoap.GetCardInfoByMCNSID(test.MCNSService.GetCardInfoByMCNSIDRequest request) {
            return base.Channel.GetCardInfoByMCNSID(request);
        }
        
        public test.MCNSService.AddCardInfo[] GetCardInfoByMCNSID(string MCNSID) {
            test.MCNSService.GetCardInfoByMCNSIDRequest inValue = new test.MCNSService.GetCardInfoByMCNSIDRequest();
            inValue.Body = new test.MCNSService.GetCardInfoByMCNSIDRequestBody();
            inValue.Body.MCNSID = MCNSID;
            test.MCNSService.GetCardInfoByMCNSIDResponse retVal = ((test.MCNSService.MCNSServiceSoap)(this)).GetCardInfoByMCNSID(inValue);
            return retVal.Body.GetCardInfoByMCNSIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.MCNSService.GetAllTempMagneticCardBasicInfoResponse test.MCNSService.MCNSServiceSoap.GetAllTempMagneticCardBasicInfo(test.MCNSService.GetAllTempMagneticCardBasicInfoRequest request) {
            return base.Channel.GetAllTempMagneticCardBasicInfo(request);
        }
        
        public test.MCNSService.MagneticCardBasicInfo[] GetAllTempMagneticCardBasicInfo() {
            test.MCNSService.GetAllTempMagneticCardBasicInfoRequest inValue = new test.MCNSService.GetAllTempMagneticCardBasicInfoRequest();
            inValue.Body = new test.MCNSService.GetAllTempMagneticCardBasicInfoRequestBody();
            test.MCNSService.GetAllTempMagneticCardBasicInfoResponse retVal = ((test.MCNSService.MCNSServiceSoap)(this)).GetAllTempMagneticCardBasicInfo(inValue);
            return retVal.Body.GetAllTempMagneticCardBasicInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.MCNSService.GetMagneticCardBasicInfoByCompanyResponse test.MCNSService.MCNSServiceSoap.GetMagneticCardBasicInfoByCompany(test.MCNSService.GetMagneticCardBasicInfoByCompanyRequest request) {
            return base.Channel.GetMagneticCardBasicInfoByCompany(request);
        }
        
        public test.MCNSService.MagneticCardBasicInfo[] GetMagneticCardBasicInfoByCompany(string CompanyName) {
            test.MCNSService.GetMagneticCardBasicInfoByCompanyRequest inValue = new test.MCNSService.GetMagneticCardBasicInfoByCompanyRequest();
            inValue.Body = new test.MCNSService.GetMagneticCardBasicInfoByCompanyRequestBody();
            inValue.Body.CompanyName = CompanyName;
            test.MCNSService.GetMagneticCardBasicInfoByCompanyResponse retVal = ((test.MCNSService.MCNSServiceSoap)(this)).GetMagneticCardBasicInfoByCompany(inValue);
            return retVal.Body.GetMagneticCardBasicInfoByCompanyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.MCNSService.AddCardResponse test.MCNSService.MCNSServiceSoap.AddCard(test.MCNSService.AddCardRequest request) {
            return base.Channel.AddCard(request);
        }
        
        public string AddCard(test.MCNSService.AddCardInfo info) {
            test.MCNSService.AddCardRequest inValue = new test.MCNSService.AddCardRequest();
            inValue.Body = new test.MCNSService.AddCardRequestBody();
            inValue.Body.info = info;
            test.MCNSService.AddCardResponse retVal = ((test.MCNSService.MCNSServiceSoap)(this)).AddCard(inValue);
            return retVal.Body.AddCardResult;
        }
    }
}
